---
- name: Install nginx-mod-dav-ext dependencies
  package:
    name:
      - nginx-src
      - libxslt
      - libutil-linux

- name: Check whether nginx-mod-dav-ext is installed
  command:
    cmd: pacman -Q nginx-mod-dav-ext
  changed_when: false
  register: dav_ext_pacman_status
  failed_when: dav_ext_pacman_status.rc not in (0, 1)

- name: Build and install nginx-mod-dav-ext
  aur:
    name: nginx-mod-dav-ext
  become: true
  become_user: "{{ aur_builder_user }}"

- name: Load nginx-mod-dav-ext module
  template:
    src: nginx_dav_ext_module.conf
    dest: /etc/nginx/modules.load.d/dav_ext.conf
    mode: 0644
    owner: root
    group: http
  notify: Reload nginx

- name: Add nginx configuration for media
  template:
    src: nginx_media.conf
    dest: /etc/nginx/sites-enabled/media.conf
    mode: 0640
    owner: root
    group: http
  notify: Reload nginx

- name: Add web_media basic authorization credentials
  template:
    src: web_media.htpasswd
    dest: /etc/nginx/snippets/
    mode: 0640
    owner: root
    group: http
  notify: Reload nginx
