---
- hosts: ub4
  become: true
  roles:
    - role: common
      tags: [common]
    - docker
    - role: web
      tags: [web]
    - name: rsshub
      vars:
        domain_name: "rsshub.{{ top_domain_name }}"
        https_certificate_path: "/etc/ssl_certificates/rsshub.{{ top_domain_name }}/fullchain.pem"
        https_key_path: "/etc/ssl_certificates/rsshub.{{ top_domain_name }}/privkey.pem"
      tags: rsshub
    - role: nas
      tags: [nas]
      vars:
        shared_paths: "{{ nfs_shared_paths }}"
    - role: borg_backup_target
      tags: [borg_backup_target]
    - role: tor
      tags: [tor]
    - role: monitoring_node
      vars:
        nginx_status_host: localhost
        nginx_status_path: /basic_status
        nginx_status_port: 80
      tags: [monitoring_node]
    - role: monitoring_server
      vars:
        prometheus_targets:
          node:
            - targets: "{{ groups['monitored_nodes'] | map('extract', hostvars, 'collectd_exporter_url') | list }}"
            - targets: [localhost:5054]
            - targets: [localhost:3000]
            - targets: [alarm.lan:5064]
        grafana_domain_name: "grafana.{{ top_domain_name }}"
        grafana_https_certificate_path: "/etc/ssl_certificates/grafana.{{ top_domain_name }}/fullchain.pem"
        grafana_https_key_path: "/etc/ssl_certificates/grafana.{{ top_domain_name }}/privkey.pem"
      tags: [monitoring_server]
    - role: https
      tags: https
    - role: borg_backup
      tags: [borg_backup]
  tasks:
    - name: Add authorized_keys to root
      authorized_key:
        key: "{{ item }}"
        user: root
      with_file:
        - authorized_keys/gileri_ryz
        - authorized_keys/gileri_tpy

    - name: Install stress tui
      pacman:
        name: s-tui

    - name: Bind mount NAS folder to IPFS home directory
      file:
        state: link
        src: /mnt/data
        path: "{{ ipfs_home }}/data"
      tags: [real_machine]

    # SSD hardware bug workaround
    - name: read-write watchdog
      tags: [rw-watchdog]
      block:
        - name: Add read-only watchdog script
          copy:
            src: templates/rw-watchdog.sh.j2
            dest: /usr/local/bin/rw-watchdog
            mode: 0755
        - name: Add read-only watchdog service
          copy:
            src: templates/rw-watchdog.service.j2
            dest: /etc/systemd/system/rw-watchdog.service
        - name: Add read-only watchdog timer
          copy:
            src: templates/rw-watchdog.timer.j2
            dest: /etc/systemd/system/rw-watchdog.timer
        - name: Start and enable read-only watchdog timer
          systemd:
            name: rw-watchdog.timer
            state: started
            enabled: true
            daemon_reload: true

    - name: Create backup folder
      file:
        state: directory
        path: /mnt/data/backup
        owner: root
        group: root
        mode: 0755

    - name: Create ph2 backup folder
      file:
        state: directory
        path: /mnt/data/backup/ph2
        owner: ph2_backup
        group: ph2_backup
        mode: 0750
