---
- hosts: ub4
  become: true
  pre_tasks:
    - name: Bind-mount rtorrent var directory
      file:
        state: link
        src: /mnt/data/dl
        path: "{{ rtorrent_var_dir }}"
      tags: [real_machine]
  roles:
    - role: common
      tags: [common]
    - docker
    - role: web
      tags: [web]
    - role: ipfs
      vars:
        ipfs_autonat_service_mode: disabled
        ipfs_filestore_enabled: "true"
      tags: [ipfs]
    - name: rsshub
      vars:
        domain_name: "rsshub.{{ top_domain_name }}"
        https_certificate_path: "/etc/ssl_certificates/rsshub.{{ top_domain_name }}/fullchain.pem"
        https_key_path: "/etc/ssl_certificates/rsshub.{{ top_domain_name }}/privkey.pem"
      tags: rsshub
    - role: nas
      tags: [nas]
      vars:
        shared_paths: "{{ nfs_shared_paths }}"
    - role: borg_backup_target
      tags: [borg_backup_target]
    - role: tor
      tags: [tor]
    - role: monitoring_node
      vars:
        nginx_status_host: localhost
        nginx_status_path: /basic_status
        nginx_status_port: 80
      tags: [monitoring_node]
    - role: monitoring_server
      vars:
        prometheus_targets:
          node:
            - targets: "{{ groups['monitored_nodes'] | map('extract', hostvars, 'collectd_exporter_url') | list }}"
        grafana_domain_name: "grafana.{{ top_domain_name }}"
        grafana_https_certificate_path: "/etc/ssl_certificates/grafana.{{ top_domain_name }}/fullchain.pem"
        grafana_https_key_path: "/etc/ssl_certificates/grafana.{{ top_domain_name }}/privkey.pem"
      tags: [monitoring_server]
    - role: https
      tags: https
    - role: borg_backup
      tags: [borg_backup]
  tasks:
    - name: Add authorized_keys to root
      authorized_key:
        key: "{{ item }}"
        user: root
      with_file:
        - authorized_keys/gileri_ryz
        - authorized_keys/gileri_tpy

    - name: Install stress tui
      pacman:
        name: s-tui

    - name: Bind mount NAS folder to IPFS home directory
      file:
        state: link
        src: /mnt/data
        path: "{{ ipfs_home }}/data"
      tags: [real_machine]
