---
- import_role:
    name: ansible-prometheus

- import_role:
    name: ansible-grafana
  vars:
    grafana_server:
      protocol: socket
      socket: "{{ grafana_socket_path }}"
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false

- name: Add web server to grafana group
  user:
    name: "{{ web_server_user }}"
    groups: grafana
    append: true

- name: Copy reverse proxy configuration
  template:
    src: templates/nginx_grafana.conf.j2
    dest: /etc/nginx/sites-enabled/grafana.conf
  when: web_server is defined and web_server == 'nginx'
  notify: Reload nginx
