---
- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Restart openethereum daemon
  systemd:
    name: openethereum.service
    state: restarted

- name: Restart beacon node service
  systemd:
    name: beacon-node.service
    state: restarted

- name: Restart validator service
  systemd:
    name: validator.service
    state: restarted
