---
- name: Install and configure hddtemp
  block:
    - name: Install hddtemp
      package:
        name: hddtemp
    - name: Create override folder
      file:
        path: /etc/systemd/system/
    - name: Create systemd service override folder
      file:
        path: /etc/systemd/system/hddtemp.service.d/
        state: directory
    - name: Create hddtemp unit override
      template:
        src: templates/hddtemp.service.override.j2
        dest: /etc/systemd/system/hddtemp.service.d/override.conf
      notify:
        - Reload systemd services
        - Restart hddtemp
    - name: Enable and start hddtemp
      systemd:
        name: hddtemp.service
        state: started
        enabled: true
  when: hddtemp_monitored_disks | length > 0

- name: Install packages
  pacman:
    name:
      - collectd
      - protobuf-c  # write_prometheus plugin
      - liboping  # ping plugin

- name: Create collectd.d directory
  file:
    path: /etc/collectd.d
    state: directory

- name: Copy collectd configuration
  template:
    src: templates/collectd.conf.j2
    dest: /etc/collectd.conf
  notify: Reload collectd

- name: Enable and start collectd
  systemd:
    name: collectd
    state: started
    enabled: true

- name: Allow pulling from collectd in firewall
  ufw:
    rule: allow
    to_port: "{{ collectd_exporter_port }}"
  when: firewall is defined and firewall == "ufw"
