---
- name: make .ipfs-cluster directory
  file:
    state: directory
    mode: 0700
    owner: "{{ ipfs_user_name }}"
    group: "{{ ipfs_user_name }}"
    dest: "{{ ipfs_home }}/.ipfs-cluster"

- name: copy configuration
  template:
    src: "{{ item }}"
    dest: "{{ ipfs_home }}/.ipfs-cluster/{{ item }}"
    mode: 0600
    owner: "{{ ipfs_user_name }}"
    group: "{{ ipfs_user_name }}"
  tags:
    - config
  with_items:
    - identity.json
    - service.json
  notify: restart IPFS Cluster

- name: set version file (to notify restart on upgrades)
  copy:
    content: "{{ ipfs_cluster_version }}"
    dest: "{{ ipfs_home }}/cluster_deployed_version"
    mode: 0644
    owner: "{{ ipfs_user_name }}"
    group: "{{ ipfs_user_name }}"
  notify: restart IPFS Cluster

- name: copy peerstore
  template:
    src: peerstore
    dest: "{{ ipfs_home }}/.ipfs-cluster/peerstore"
    mode: 0600
    owner: "{{ ipfs_user_name }}"
    group: "{{ ipfs_user_name }}"
    force: false
  tags:
    - config
  notify: restart IPFS Cluster
