---
- name: Create a dedicated user
  user:
    name: "{{ user_name }}"
    create_home: yes

- name: Install IPFS
  pacman:
    name: go-ipfs
  when: ansible_facts["os_family"] == "Archlinux"
  notify: Restart ipfs systemd service

- name: Start and enable ipfs systemd service
  systemd:
    state: started
    enabled: yes
    name: ipfs@{{ user_name }}
    daemon_reload: yes
