---
ipfs_addresses_swarm:
  - "/ip4/0.0.0.0/tcp/4001"
  - "/ip6/::/tcp/4001"
  - "/ip4/0.0.0.0/udp/4001/quic"
  - "/ip6/::/udp/4001/quic"
ipfs_api_address: /ip4/127.0.0.1/tcp/5001
ipfs_autonat_service_mode: enabled
ipfs_api_http_headers: {}
ipfs_daemon_flags: "--enable-gc --enable-pubsub-experiment --enable-namesys-pubsub"
ipfs_gateway_sites: {}
ipfs_filestore_enabled: "false"  # Must be string to stay a valid json value
ipfs_no_fetch: true
ipfs_no_dnslink: true
ipfs_gateway_address: /ip4/127.0.0.1/tcp/8080
ipfs_gateway_host: 127.0.0.1
ipfs_gateway_port: 8080
ipfs_profiles: server
ipfs_storage_max: "10GB"
ipfs_user_name: ipfs
ipfs_group_name: ipfs
ipfs_home: /home/ipfs
ipfs_path: "{{ ipfs_home }}/ipfs"
