---
- name: Install certbot
  pacman:
    name: certbot

- name: Create challenge directory
  file:
    state: directory
    owner: root
    group: http
    mode: u=rwx,g=rx,o=
    path: "{{ acme_challenge_directory }}"

- name: Generate certificates
  command:
    cmd: >-
      certbot certonly --webroot --noninteractive --agree-tos
      --email "{{ acme_email }}" -d "{{ item }}"
      --webroot-path "{{ acme_challenge_directory }}"
    creates: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
  loop: "{{ https_domains }}"

- name: Deploy live certificates
  file:
    state: link
    src: "/etc/letsencrypt/live/{{ item.item }}"
    path: "{{ certificates_live_dir }}/{{ item.item }}"
  loop: "{{ https_stat_placeholders.results }}"
  when: item.stat.lnk_source != "/etc/letsencrypt/live/" + item.item
  notify: Reload nginx

- name: Create certbot renewal systemd unit
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - certbot-renew.service
    - certbot-renew.timer

- name: Enable certbot renewal systemd timer
  systemd:
    name: certbot-renew.timer
    daemon_reload: true
    enabled: true
    state: started
