---
- name: Pull docker image
  docker_image:
    name: "{{ docker_image_tag }}"
    source: pull

- name: Copy systemd service
  template:
    src: templates/rsshub.service
    dest: /etc/systemd/system/rsshub.service
  register: systemd_service_file

- name: Reload systemd services
  systemd:
    daemon_reload: true
  when: systemd_service_file.changed

- name: Create container
  docker_container:
    image: "{{ docker_image_tag }}"
    env:
      UA: "{{ rsshub_user_agent }}"
    user: "9999"
    name: "{{ docker_container_name }}"
    ports: "{{ docker_container_host_host }}:{{ docker_container_host_port }}:1200"
    state: present

- name: Enable and start systemd service
  systemd:
    name: rsshub.service
    state: started
    enabled: true

- name: Add nginx htpasswd
  template:
    src: templates/rsshub.htpasswd
    dest: /etc/nginx/snippets/
    owner: root
    group: http
    mode: 0640
  notify: Reload nginx

- name: Add nginx site
  template:
    src: templates/rsshub.conf
    dest: /etc/nginx/sites-enabled/
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx
