---
- name: Install PHP
  pacman:
    name:
      - php
      - php-fpm

- name: Enable and start php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: true

- name: Install nginx
  pacman:
    name: nginx

- name: Generate dhparams
  openssl_dhparam:
    path: /etc/nginx/dhparams.pem
    size: 4096

- name: Create modules.load.d directory
  file:
    path: /etc/nginx/modules.load.d
    state: directory
    owner: root
    group: http
    mode: 0755

- name: Configure nginx conf
  copy:
    src: templates/nginx/conf.d
    dest: /etc/nginx/
  notify:
    - Reload nginx

- name: Configure nginx main conf
  copy:
    src: templates/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload nginx

- name: Configure nginx snippets
  copy:
    src: templates/nginx/snippets
    dest: /etc/nginx/
  notify:
    - Reload nginx

- name: Configure nginx sites
  copy:
    src: templates/nginx/sites-enabled
    dest: /etc/nginx/
  notify:
    - Reload nginx

- name: Enable and start nginx
  systemd:
    name: nginx
    state: started
    enabled: true

- name: Allow public access to nginx in firewall
  ufw:
    rule: allow
    to_port: "{{ item }}"
  loop:
    - "80"
    - "443"
