---
- name: Generate locale
  locale_gen:
    name: fr_FR.UTF-8

- name: Set default locale
  lineinfile:
    line: LANG=fr_FR.UTF-8
    path: /etc/locale.conf

- name: Synchronize time
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: true

- name: Add groups
  group:
    name: "{{ item }}"
  loop: "{{ host_groups }}"

- name: Add users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    home: "{{ item.home | default('/home/' + item.name) }}"
  loop: "{{ host_users }}"

- name: Add SSH authorized keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.key }}"
    key_options: "{{ item.1.key_options | default('') }}"
  loop: "{{ host_users | subelements('authorized_keys', skip_missing=True) }}"

- name: Upgrade packages
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  pacman:
    name:
      - base-devel
      - git
      - neovim
      - openssh
      - reflector
      - lm_sensors
      - zsh-completions
      - btrfs-progs
      - htop
      - tmux
      - mosh
      - ufw
      - tcpdump
      - strace
      - ranger
      - rsync
      - ncdu
      - smartmontools
      - gnu-netcat
      - mediainfo
      - lsof
      - gptfdisk
      - man
      - unzip
      - unrar
      - iotop
      - sysstat
      - conntrack-tools

- name: Create aur_builder_user
  user:
    name: "{{ aur_builder_user }}"
    create_home: false
    group: wheel

- name: Allow aur_builder_user to run pacman
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "{{ aur_builder_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: 'visudo -cf %s'

- name: Check whether there is a mirrorlist.pacnew
  stat:
    path: /etc/pacmand.d/mirrorlist.pacnew
  register: mirrorlist_pacnew

- name: Update mirrorlist
  copy:
    remote_src: true
    src: /etc/pacman.d/mirrorlist.pacnew
    dest: /etc/pacman.d/mirrorlist
  when: mirrorlist_pacnew.stat.exists

- name: Rank mirrors
  shell:
    command: reflector --country France --latest 200 --age 2 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
  when: mirrorlist_pacnew.stat.exists

- name: Enable and start sshd socket  # Duh
  systemd:
    name: sshd.service
    state: started
    enabled: true

- name: Disable SSH passphrase-based login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no
    regexp: '^#?PasswordAuthentication.*(yes|no)'
  notify: Reload sshd

- name: Allow SSH in firewall
  ufw:
    rule: allow
    to_port: ssh
    proto: tcp

- name: Configure and enable ufw
  ufw:
    default: deny
    state: enabled
    logging: "off"

- name: Enable ufw at boot
  systemd:
    name: ufw
    enabled: true

- name: Add additional ufw rules
  ufw:
    from_ip: "{{ item.from_ip }}"
    proto: "{{ item.proto }}"
    rule: "{{ item.rule }}"
    to_port: "{{ item.to_port }}"
  loop: "{{ ufw_additional_rules | default([]) }}"
