---
- name: Generate locale
  locale_gen:
    name: fr_FR.UTF-8

- name: Set default locale
  lineinfile:
    line: LANG=fr_FR.UTF-8
    path: /etc/locale.conf

- name: Synchronize time
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: true

- name: Upgrade packages
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  pacman:
    name:
      - base-devel
      - git
      - neovim
      - openssh
      - reflector
      - lm_sensors
      - zsh-completions
      - btrfs-progs
      - htop
      - tmux
      - mosh
      - ufw
      - tcpdump
      - strace
      - ranger
      - rsync
      - ncdu
      - smartmontools
      - gnu-netcat
      - mediainfo
      - lsof
      - gptfdisk
      - man
      - unzip
      - unrar
      - iotop
      - sysstat

- name: Create aur_builder user
  user:
    name: aur_builder

- name: Check whether there is a mirrorlist.pacnew
  stat:
    path: /etc/pacmand.d/mirrorlist.pacnew
  register: mirrorlist_pacnew

- name: Update mirrorlist
  copy:
    remote_src: true
    src: /etc/pacman.d/mirrorlist.pacnew
    dest: /etc/pacman.d/mirrorlist
  when: mirrorlist_pacnew.stat.exists

- name: Rank mirrors
  shell:
    command: reflector --country France --latest 200 --age 2 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
  when: mirrorlist_pacnew.stat.exists

- name: Enable and start sshd socket  # Duh
  systemd:
    name: sshd.service
    state: started
    enabled: true

- name: Disable SSH passphrase-based login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no
    regexp: '^#?PasswordAuthentication.*(yes|no)'
  notify: Reload sshd

- name: Allow SSH in firewall
  ufw:
    rule: allow
    to_port: ssh
    proto: tcp

- name: Configure and enable ufw
  ufw:
    default: deny
    state: enabled
    logging: "off"

- name: Enable ufw at boot
  systemd:
    name: ufw
    enabled: true
